	OUTPUT	demo.com
	ORG	0x0100

; BIOS entry points
BIOS_TICK	EQU	0xFDC7		; HL -> handler

; CP/M entry points
IOBYTE		EQU	0x0003
BDOS		EQU	0x0005

; BDOS function codes
GETIO		EQU	7
SETIO		EQU	8


entry
; stop BIOS mucking about with the display
; IOBYTE structure:
; Bits 0,1: CONSOLE
; Bits 2,3: READER
; Bits 4,5: PUNCH
; Bits 6,7: LIST
		LD	C, GETIO
		CALL	BDOS
		AND	0b11111100
		OR	0b00000010   ; Set Console bits to 10 (BAT: mode)
		LD	C, SETIO
		LD	E, A
		CALL	BDOS




		LD	HL, demo_stream
		CALL	segfx_init
		LD	HL, segfx_tick
		CALL	BIOS_TICK

loop		HALT			; give segfx_update a chance to run
		CALL	segfx_update
		JP	loop

	DEFINE	SEGFX_RAM_BASE $
	INCLUDE	"segfx.asm"	

	MACRO	PAGE in?, disp?, out?, spd?, dwell?, msg?
		DB	PAGE_START
		DB	in?
		DB	disp?
		DB	out?
		DB	spd? 
		DW	dwell?
		DB 	msg?
		DB      PAGE_END
	ENDM

		
STD_SPEED	EQU	1
SLOW_SPEED	EQU	3

demo_stream
		PAGE	TRANS_FADE, DISP_STATIC, TRANS_FADE, STD_SPEED, 200, <INL_ALIGN_C, "* Feersum Technology *">
		PAGE	TRANS_FADE, DISP_STATIC, TRANS_FADE, STD_SPEED, 200, <INL_ALIGN_C, INL_CHARDEF, 0xA1, 0xC9, 0x00, "-=", 0xA1, " presents ", 0xA1, "=-"> 
		PAGE	TRANS_DISSOLVE, DISP_WAVE, TRANS_DISSOLVE, STD_SPEED, 200, <INL_ALIGN_C, INL_WAVE_TBL, INL_PARAM_BASE + 1, INL_WAVE_DIR, INL_PARAM_BASE + 2, INL_CHARDEF, 0xA0, 0x3E, 0x05, 0xA0, "  MICROBEAST  ", 0xA0>
		PAGE	TRANS_VFADE_D, DISP_SCROLL_L, TRANS_VFADE_U, SLOW_SPEED, 200, "Standalone Z80 kit computer, running CP/M"
		PAGE	TRANS_VFADE_U, DISP_SCROLL_L, TRANS_VFADE_D, SLOW_SPEED, 200, "24 character, 14 segment display + virtual console"
		PAGE	TRANS_NONE, DISP_TYPEWRITER, TRANS_NONE, SLOW_SPEED, 200, <INL_ALIGN_C, "47-key keyboard">
		PAGE	TRANS_WIPE_L, DISP_SCROLL_L, TRANS_WIPE_L, SLOW_SPEED, 300, "Z80 CPU 8-10MHz  /  512K RAM  /  512k Flash ROM"
		PAGE	TRANS_NONE, DISP_BOUNCE, TRANS_NONE, SLOW_SPEED, 300, "    Power and data over USB-C. One cable does it all    "
		PAGE	TRANS_NONE, DISP_BOUNCE, TRANS_NONE, SLOW_SPEED, 300, "    Battery backed real time clock    "
		PAGE	TRANS_NONE, DISP_MARQUEE_L, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 10, "Runs ", INL_BRIGHT, INL_PARAM_BASE + 15, "CP/M">
		PAGE	TRANS_NONE, DISP_MARQUEE_R, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 10, "Custom ", INL_BRIGHT, INL_PARAM_BASE + 15, "BIOS">
		PAGE	TRANS_NONE, DISP_MARQUEE_L, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 10, "12 ", INL_BRIGHT, INL_PARAM_BASE + 15, "GPIO ", INL_BRIGHT, INL_PARAM_BASE + 10, "pins">
		PAGE	TRANS_NONE, DISP_MARQUEE_R, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 15, "RC2014 ", INL_BRIGHT, INL_PARAM_BASE + 10, "compatible">
		PAGE	TRANS_NONE, DISP_MARQUEE_L, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 15, "FTDI ", INL_BRIGHT, INL_PARAM_BASE + 10, "header">
		PAGE	TRANS_NONE, DISP_MARQUEE_R, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 15, "Speaker ", INL_BRIGHT, INL_PARAM_BASE + 10, "+ aux power">
		PAGE	TRANS_NONE, DISP_MARQUEE_L, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 15, "I2C ", INL_BRIGHT, INL_PARAM_BASE + 10, " header">
		PAGE	TRANS_NONE, DISP_MARQUEE_R, TRANS_NONE, STD_SPEED, 200, <INL_ALIGN_C, INL_BRIGHT, INL_PARAM_BASE + 15, INL_CHARDEF, 0xA2, 0xDC, 0x05, 0xA2, " VideoBeast ", 0xA2, INL_BRIGHT, INL_PARAM_BASE + 10, " ready">

		PAGE	TRANS_FADE_WP_L, DISP_BREATHE, TRANS_FADE_WP_L, STD_SPEED, 200, <INL_ALIGN_C, INL_FLASH, "Unique ", INL_NOFLASH, "kit in a box!">
		PAGE	TRANS_FADE_WP_R, DISP_SPARKLE, TRANS_FADE_WP_R, STD_SPEED, 200, <INL_ALIGN_C, "Build it yourself!">

		PAGE	TRANS_WIPE_CTR, DISP_WAVE, TRANS_WIPE_CTR, STD_SPEED, 200, <INL_ALIGN_C, "Stylish!">
		PAGE	TRANS_WIPE_L, DISP_WAVE, TRANS_WIPE_R, STD_SPEED, 200, <INL_ALIGN_C, INL_WAVE_TBL, INL_PARAM_BASE + 2, "Functional!!">
		PAGE	TRANS_VFADE_U, DISP_WAVE, TRANS_VFADE_D, STD_SPEED, 300, <INL_ALIGN_C, INL_WAVE_TBL, INL_PARAM_BASE + 3, "Powerful!!!">
		PAGE	TRANS_VFADE_D, DISP_WAVE, TRANS_VFADE_U, STD_SPEED, 300, <INL_ALIGN_C, INL_WAVE_TBL, INL_PARAM_BASE + 4, "Made in the UK">
		DB	END_STREAM